<?php

namespace App\Models;

use App\Services\FinanceService\FinanceService;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Log;

class Operation extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public const OPERATION_DEBIT = 'debit';

    public const OPERATION_CREDIT = 'credit';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Operation $operation) {

        });
    }


    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function getOperationAttribute(): string
    {
        return match ($this->type) {
            self::OPERATION_DEBIT => 'Начисление',
            self::OPERATION_CREDIT => 'Списание',
            default => $this->type,
        };
    }


    public static function getLastOperations(User $user, ?int $limit = 5)
    {
        Log::info('Limit', [$limit]);
        return $user->operations()->orderByDesc('operation_date')
            ->when($limit, function (Builder $builder) use ($limit){
                return $builder->take($limit);
            })->get();
    }

}
